package id.pawra.ui.screen.pet.profile


data class DogAddFormState(
    val name: String = "",
    val nameError: String? = null,
    val breed: String = "",
    val breedError: String? = null,
    val neutered: Boolean = false,
    val year: String = "",
    val yearError: String? = null,
    val height: String = "",
    val heightError: String? = null,
    val sex: String = "Male",
    val weight: String = "",
    val weightError: String? = null,
    val color: String = "",
    val colorError: String? = null,
    val microchipId: String = "",
    val microchipIdError: String? = null,
    val summary: String = "",
    val summaryError: String? = null,
    var file: String = "",
    val fileError: String? = null,
)

data class DogUpdateFormState(
    var id: Int = 0,
    var name: String = "",
    val nameError: String? = null,
    var breed: String = "",
    val breedError: String? = null,
    var neutered: Boolean = false,
    var year: String = "",
    val yearError: String? = null,
    var height: String = "",
    val heightError: String? = null,
    var sex: String = "Male",
    var weight: String = "",
    val weightError: String? = null,
    var color: String = "",
    val colorError: String? = null,
    var microchipId: String = "",
    val microchipIdError: String? = null,
    var summary: String = "",
    val summaryError: String? = null,
    var file: String = "",
    val fileError: String? = null,
)